// import type { Metadata } from "next";
// import { Inter } from "next/font/google";
// // import "../../app/globals.css";
// import Navbar from "@/presentation/components/Navbar";
// import Sidebar from "@/presentation/components/Sidebar";

// const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <div>
     
//          <body className={inter.className}>
        
//         <div className="">
          
//       <Navbar />
//         </div>
//         <div className=" flex">
     
//     <Sidebar/>
//           {children} 
//           </div>
  
//           </body>
//     </div>
//   );
// }
'use client'
import {useState} from 'react';
export default function Layout({ children }:{ children: React.ReactNode }) {
const [input, setInput] = useState("");
return (
    <div>
      {children}
    </div>
  );
}