import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/presentation/components/Navbar";
import Sidebar from "@/presentation/components/Sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* <body className={inter.className}>
        
        
        {children}
        
        </body> */}
         <body className={inter.className}>
        
        <div className="">
          
      <Navbar />
        </div>
        <div className=" flex">
     
    <Sidebar/>
          {children} 
          </div>
  
          </body>
    </html>
  );
}
